services:
  app:
    image: fms-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fms-api
    ports:
      - 5000:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: fms-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: