services:
  fms-api:
    image: ghcr.io/laubertarelli/fms-api:latest
    container_name: fms-api
    depends_on:
      - fms-db
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=fms-db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    networks:
      - fms_net
      - caddy_net

  fms-db:
    image: postgres:16
    container_name: fms-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fms_net

volumes:
  pgdata:

networks:
  fms_net:
  caddy_net:
    external: true