import { reactive } from "vue";

export default reactive({
    //token: ""
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyYzFlZjMzYy03MTUyLTQ3NzctODE3Mi05ZDA2MzllYTg2ZDgiLCJ1bmlxdWVfbmFtZSI6ImxhdXRhYmVyOSIsImVtYWlsIjoibGF1dGFiZXI5QGdtYWlsLmNvbSIsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvbGUiOiJhZG1pbiIsIm5iZiI6MTczODU2ODU0NiwiZXhwIjoxNzM4NjU0OTQ2LCJpYXQiOjE3Mzg1Njg1NDZ9.s9GYnxmkt6Z6RxkTbaJPePF7ZN4PvqDAC4wnpaYQf2s"
});