import { reactive } from "vue";

export default reactive({
    //token: ""
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyYzFlZjMzYy03MTUyLTQ3NzctODE3Mi05ZDA2MzllYTg2ZDgiLCJ1bmlxdWVfbmFtZSI6ImxhdXRhYmVyOSIsImVtYWlsIjoibGF1dGFiZXI5QGdtYWlsLmNvbSIsInBlcm1pc3Npb24iOlsiY3JlYXRlIiwidXBkYXRlIiwiZGVsZXRlIl0sInJvbGUiOiJhZG1pbiIsIm5iZiI6MTczODY1NTI5OCwiZXhwIjoxNzM4NzQxNjk4LCJpYXQiOjE3Mzg2NTUyOTh9.292etbkLM1J6RkUMJI3e0RCpFnRrBB8H2VX8kKe0x3Y"
});